final Map<String, dynamic> plantData = {
  "categories": [
    {"id": 1, "name": "Piante grasse"},
    {"id": 2, "name": "Piante da interno"},
    {"id": 3, "name": "Piante da esterno"},
    {"id": 4, "name": "Erbe aromatiche"},
    {"id": 5, "name": "Piante fiorite"},
  ],
  "plants": [
    {
      "id": 1,
      "name": "Aloe Vera",
      "species": "Aloe barbadensis miller",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Aloe_Vera.jpg/1200px-Aloe_Vera.jpg?20051224024927",
      "description":
          "Pianta succulenta nota per le sue proprietà lenitive e cicatrizzanti.",
      "planted_on": "09/07/2025",
      "category_id": 1,
      "watering_frequency": "30",
      "pruning_frequency": "20",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 2,
      "name": "Ficus Benjamina",
      "species": "Ficus benjamina",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/BBG_-_Ficus_benjamina_-_Forrest.jpg/640px-BBG_-_Ficus_benjamina_-_Forrest.jpg",
      "description": "Pianta ornamentale molto diffusa negli ambienti interni.",
      "planted_on": "12/05/2024",
      "category_id": 2,
      "watering_frequency": "10",
      "pruning_frequency": "60",
      "transfer_frequency": "730",
      "note": "",
    },
    {
      "id": 3,
      "name": "Rosmarino",
      "species": "Salvia rosmarinus",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Rosmarinus_officinalis133095382.jpg/640px-Rosmarinus_officinalis133095382.jpg",
      "description": "Erba aromatica molto usata in cucina, ama il sole.",
      "planted_on": "01/04/2025",
      "category_id": 4,
      "watering_frequency": "7",
      "pruning_frequency": "90",
      "transfer_frequency": "180",
      "note": "",
    },
    {
      "id": 4,
      "name": "Cactus Pera Spinosa",
      "species": "Opuntia ficus-indica",
      "image":
          "https://www.plantazon.it/media/catalog/product/cache/3a7af0a8e0e317723249dc9098669163/f/d/fd18063wh.jpg",
      "description":
          "Cactus originario del Messico, produce frutti chiamati fichi d'India.",
      "planted_on": "15/03/2023",
      "category_id": 1,
      "watering_frequency": "60",
      "pruning_frequency": "120",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 5,
      "name": "Basilico",
      "species": "Ocimum basilicum",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ocimum_Basilicum_leaf_lighted_by_the_left.jpg/640px-Ocimum_Basilicum_leaf_lighted_by_the_left.jpg",
      "description":
          "Erba annuale molto aromatica, richiede innaffiature frequenti.",
      "planted_on": "01/06/2025",
      "category_id": 4,
      "watering_frequency": "3",
      "pruning_frequency": "30",
      "transfer_frequency": "90",
      "note": "",
    },
    {
      "id": 6,
      "name": "Lavanda",
      "species": "Lavandula angustifolia",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Single_lavender_flower02.jpg/640px-Single_lavender_flower02.jpg",
      "description": "Pianta perenne dai fiori viola profumati.",
      "planted_on": "15/05/2024",
      "category_id": 5,
      "watering_frequency": "14",
      "pruning_frequency": "120",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 7,
      "name": "Cactus",
      "species": "Echinopsis spp.",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Soehrensia_spachiana.jpg/640px-Soehrensia_spachiana.jpg",
      "description": "Pianta grassa molto resistente alla siccità.",
      "planted_on": "10/10/2023",
      "category_id": 1,
      "watering_frequency": "60",
      "pruning_frequency": "0",
      "transfer_frequency": "730",
      "note": "",
    },
    {
      "id": 8,
      "name": "Sansevieria",
      "species": "Sansevieria trifasciata",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Snake_plant.jpg/640px-Snake_plant.jpg",
      "description": "Pianta da interno resistente e decorativa.",
      "planted_on": "05/11/2024",
      "category_id": 2,
      "watering_frequency": "20",
      "pruning_frequency": "90",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 9,
      "name": "Begonia",
      "species": "Begonia semperflorens",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Begonia_cucullata_var._hookeri.jpg/640px-Begonia_cucullata_var._hookeri.jpg",
      "description": "Pianta ornamentale con fiori colorati.",
      "planted_on": "01/05/2025",
      "category_id": 5,
      "watering_frequency": "5",
      "pruning_frequency": "45",
      "transfer_frequency": "180",
      "note": "",
    },
    {
      "id": 10,
      "name": "Geranio",
      "species": "Pelargonium",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Geranium_maculatum%2C_2021-05-06%2C_Bird_Park%2C_03.jpg/640px-Geranium_maculatum%2C_2021-05-06%2C_Bird_Park%2C_03.jpg",
      "description": "Pianta fiorita molto usata nei balconi.",
      "planted_on": "01/04/2025",
      "category_id": 5,
      "watering_frequency": "3",
      "pruning_frequency": "30",
      "transfer_frequency": "180",
      "note": "",
    },
    {
      "id": 11,
      "name": "Dracena",
      "species": "Dracaena marginata",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Dragonblood_tree_in_Socotra_2.jpg/640px-Dragonblood_tree_in_Socotra_2.jpg",
      "description":
          "Pianta ornamentale da interno con foglie lunghe e sottili.",
      "planted_on": "20/03/2024",
      "category_id": 2,
      "watering_frequency": "10",
      "pruning_frequency": "120",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 12,
      "name": "Mentha",
      "species": "Mentha spicata",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Mentha_spicata_sl4.jpg/640px-Mentha_spicata_sl4.jpg",
      "description": "Erba aromatica usata per tisane e cucina.",
      "planted_on": "01/06/2025",
      "category_id": 4,
      "watering_frequency": "2",
      "pruning_frequency": "30",
      "transfer_frequency": "120",
      "note": "",
    },
    {
      "id": 13,
      "name": "Orchidea",
      "species": "Phalaenopsis",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Phalaenopsis_%28aka%29.jpg/640px-Phalaenopsis_%28aka%29.jpg",
      "description": "Pianta elegante da interno, fioritura prolungata.",
      "planted_on": "15/02/2025",
      "category_id": 2,
      "watering_frequency": "14",
      "pruning_frequency": "60",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 14,
      "name": "Pothos",
      "species": "Epipremnum aureum",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/640px-Epipremnum_aureum_31082012.jpg",
      "description": "Pianta rampicante da interno, facile da curare.",
      "planted_on": "01/05/2024",
      "category_id": 2,
      "watering_frequency": "7",
      "pruning_frequency": "90",
      "transfer_frequency": "365",
      "note": "",
    },
    {
      "id": 15,
      "name": "Citronella",
      "species": "Cymbopogon nardus",
      "image":
          "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cymbopogon_citratus_leaves.jpg/640px-Cymbopogon_citratus_leaves.jpg",
      "description": "Pianta aromatica utile contro le zanzare.",
      "planted_on": "01/06/2025",
      "category_id": 3,
      "watering_frequency": "5",
      "pruning_frequency": "30",
      "transfer_frequency": "180",
      "note": "",
    },
  ],
};
